version: '3.4'

networks:
  s3apitesttask-back-network:
    driver: bridge

services:
  s3apitesttask.api:
    container_name: s3apitesttask.api
    image: ${DOCKER_REGISTRY-}s3apitesttaskapi
    build:
      context: .
      dockerfile: src/S3ApiTestTask.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - AppSettings__AllowedOrigin=http://localhost:8081
      - ConnectionStrings__Db=Host=s3apitesttask.db;Port=5432;Database=postgres;Username=postgres;Password=example
      - S3Config__InternalUrl=s3apitesttask.minio:9000
      - S3Config__ExternalUrl=localhost:9002
      - S3Config__AccessKey=MINIO_ROOT_USER_EXAMPLE
      - S3Config__SecterKey=MINIO_ROOT_PASSWORD_EXAMPLE
      - S3Config__PresignedUrlLifetime=600
      - S3Config__BucketName=files
    depends_on:
      - s3apitesttask.db
      - s3apitesttask.minio
    networks:
      - s3apitesttask-back-network
    restart: on-failure

  s3apitesttask.db:
    container_name: s3apitesttask.db
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - s3apitesttask-back-network
    volumes:
      - ..\S3ApiTestTask.Volumes\Postgres:/var/lib/postgresql/data
    restart: on-failure

  s3apitesttask.minio:
    container_name: s3apitesttask.minio
    image: minio/minio
    ports:
      - 9002:9000
      - 9003:9001
    command: server /data --console-address ":9001"
    volumes:
      - ..\S3ApiTestTask.Volumes\Minio:/data
    environment:
      MINIO_ROOT_USER: MINIO_ROOT_USER_EXAMPLE
      MINIO_ROOT_PASSWORD: MINIO_ROOT_PASSWORD_EXAMPLE
    networks:
      - s3apitesttask-back-network
    restart: on-failure
